name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Get tag from build environment
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Set package version
        run: npm version --allow-same-version --git-tag-version=false ${{ steps.tag.outputs.tag }}
      - name: Authenticate with npm
        run: npm set //registry.npmjs.org/:_authToken ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish to npm
        run: npm publish
